development:
  cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :cloud_name) || ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, :api_key) || ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, :api_secret) || ENV['CLOUDINARY_API_SECRET'] %>
  secure: true

production:
  cloud_name: <%= Rails.application.credentials.dig(:cloudinary, :cloud_name) || ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= Rails.application.credentials.dig(:cloudinary, :api_key) || ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= Rails.application.credentials.dig(:cloudinary, :api_secret) || ENV['CLOUDINARY_API_SECRET'] %>
  secure: true
